[main]
from = ["get"]
do = "go build -o target/bake bakery.go"

[get]
from = ["main"]
do = "go get github.com/BurntSushi/toml"

[install]
from = ["main"]
do = "sudo cp target/bake /usr/bin/bake"

[break]
do = "asdfghjkl"